swagger: "2.0"
info:
  title: Romana agent API
  description: |
    Agent provides access to configuration and helper functions, shared across
    all the threads.
    Types Config, Leasefile and Firewall are designed to be loosely coupled
    so they could later be separated into packages and used independently.
  contact:
    url: http://romana.io
    email: info@romana.io
  license:
    name: Apache License 2.0
    url: https://github.com/romana/core/blob/master/LICENSE
  version: 0.9.0
basePath: /
schemes:
- http
- https
consumes:
- text/plain
- application/vnd.romana.v1+json
- application/vnd.romana+json
- application/json
- application/x-www-form-urlencoded
produces:
- text/plain
- application/vnd.romana.v1+json
- application/vnd.romana+json
- application/json
- application/x-www-form-urlencoded
paths:
  /:
    post:
      summary: index
      description: |
        index handles HTTP requests for endpoints provisioning.
        Currently tested with Romana ML2 driver.
        TODO index should be reserved for an actual index, while this function
        need to be renamed as interfaceHandler and need to respond on it's own url.
      parameters:
      - name: agent.NetIf
        in: body
        description: |
          NetIf is a structure that represents
          network interface and its IP configuration
          together with basic methods operating on this structure.
        required: true
        schema:
          $ref: '#/definitions/agent.NetIf'
      responses:
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/common.HttpError'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/common.HttpError'
        "500":
          description: Unexpected error
          schema:
            $ref: '#/definitions/common.HttpError'
  /kubernetes-pod-up:
    post:
      summary: k8sPodUpHandler
      description: |
        k8sPodUpHandler handles HTTP requests for endpoints provisioning.
      parameters:
      - name: agent.NetworkRequest
        in: body
        description: |
          NetworkRequest specifies messages sent to the
          agent containing information on how to configure network
          on its host.
        required: true
        schema:
          $ref: '#/definitions/agent.NetworkRequest'
      responses:
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/common.HttpError'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/common.HttpError'
        "500":
          description: Unexpected error
          schema:
            $ref: '#/definitions/common.HttpError'
  /policies:
    get:
      summary: listPolicies
      description: |
        listPolicies is a placeholder. TODO.
      responses:
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/common.HttpError'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/common.HttpError'
        "500":
          description: Unexpected error
          schema:
            $ref: '#/definitions/common.HttpError'
    post:
      summary: addPolicy
      description: |
        addPolicy is a placeholder. TODO
      parameters:
      - name: common.Policy
        in: body
        description: |
          Policy describes Romana network security policy.
          For examples, see:
          1. https://github.com/romana/core/blob/master/policy/policy.sample.json
          2. https://github.com/romana/core/blob/master/policy/policy.example.agent.json
        required: true
        schema:
          $ref: '#/definitions/common.Policy'
      responses:
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/common.HttpError'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/common.HttpError'
        "500":
          description: Unexpected error
          schema:
            $ref: '#/definitions/common.HttpError'
    delete:
      summary: deletePolicy
      description: |
        deletePolicy is a placeholder. TODO
      parameters:
      - name: common.Policy
        in: body
        description: |
          Policy describes Romana network security policy.
          For examples, see:
          1. https://github.com/romana/core/blob/master/policy/policy.sample.json
          2. https://github.com/romana/core/blob/master/policy/policy.example.agent.json
        required: true
        schema:
          $ref: '#/definitions/common.Policy'
      responses:
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/common.HttpError'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/common.HttpError'
        "500":
          description: Unexpected error
          schema:
            $ref: '#/definitions/common.HttpError'
definitions:
  agent.NetIf:
    description: |
      NetIf is a structure that represents
      network interface and its IP configuration
      together with basic methods operating on this structure.
    type: object
    required:
    - interface_name
    properties:
      interface_name:
        type: string
      ip_address:
        type: array
        items:
          type: integer
  agent.NetworkRequest:
    description: |
      NetworkRequest specifies messages sent to the
      agent containing information on how to configure network
      on its host.
    type: object
    properties:
      net_if:
        $ref: '#/definitions/agent.NetIf'
      options:
        type: object
  common.Datacenter:
    description: |
      Datacenter represents the configuration of a datacenter.
    type: object
    required:
    - id
    - prefix_bits
    - port_bits
    - tenant_bits
    - segment_bits
    - endpoint_bits
    - endpoint_space_bits
    properties:
      cidr:
        type: string
      endpoint_bits:
        type: integer
      endpoint_space_bits:
        type: integer
      id:
        type: integer
        format: uint64
      ip_version:
        type: integer
      name:
        type: string
      port_bits:
        type: integer
      prefix:
        type: integer
        format: uint64
      prefix_bits:
        type: integer
      segment_bits:
        type: integer
      tenant_bits:
        type: integer
  common.HttpError:
    description: |
      HttpError is a structure that represents, well, an HTTP error.
    type: object
    required:
    - status_code
    - see_also
    properties:
      details:
        type: object
      resource_id:
        type: string
      resource_type:
        type: string
      see_also:
        type: string
      status_code:
        type: integer
  common.Policy:
    description: |
      Policy describes Romana network security policy.
      For examples, see:
      1. https://github.com/romana/core/blob/master/policy/policy.sample.json
      2. https://github.com/romana/core/blob/master/policy/policy.example.agent.json
    type: object
    required:
    - name
    properties:
      applied_to:
        type: array
        items: {}
      datacenter:
        $ref: '#/definitions/common.Datacenter'
      description:
        type: string
      direction:
        type: string
      external_id:
        type: string
      id:
        type: integer
        format: uint64
      name:
        type: string
      peers:
        type: array
        items: {}
      rules:
        type: array
        items: {}
