apiVersion: v1
kind: ReplicationController
metadata:
  name: c02-node01
  labels:
    app: c02-node01
spec:
  replicas: 1
  selector:
    app: c02-node01
  template:
    metadata:
      labels:
        app: c02-node01
    spec: 
      containers:
      - name: c02-node01-container
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: c02-node01
  labels:
    app: c02-node01
  annotations:
    romanaip: '{"auto": false, "ip": "192.168.99.101"}'
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: c02-node01
